<a href="https://colab.research.google.com/github/dtminnick/pytorch-practice/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition long hand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
# Subtract long
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [7]:
# Multiply
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
torch.divide(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [12]:
# Reminder long
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [13]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [14]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
# Reassignment
tensor_a + tensor_b

# tensor_a = tensor_a + tensor_b

tensor_a.add_(tensor_b)

tensor_a

tensor([ 6,  8, 10, 12])