<a href="https://colab.research.google.com/github/dtminnick/pytorch-practice/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

Lists

In [3]:
my_list = [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays

In [4]:
np1 = np.random.rand(3, 4)
np1

array([[0.1643271 , 0.71072354, 0.10110643, 0.30863258],
       [0.59538441, 0.0124863 , 0.39984288, 0.95342836],
       [0.53755047, 0.90222441, 0.28480338, 0.32170616]])

In [5]:
np1.dtype

dtype('float64')

Tensors

In [6]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-1.0233,  0.9667, -1.4241, -0.2476],
        [ 1.3669,  0.9348,  0.9790, -0.5822],
        [ 0.5801, -0.2567, -0.2932,  0.7529]])

In [8]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensor from numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1643, 0.7107, 0.1011, 0.3086],
        [0.5954, 0.0125, 0.3998, 0.9534],
        [0.5376, 0.9022, 0.2848, 0.3217]], dtype=torch.float64)